repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-yaml
    # -   id: end-of-file-fixer
    -   id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
    - id: black
      language_version: python3.9
      args: [--line-length=131]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies: [flake8-docstrings, pep8-naming]
        # args: ["--max-line-length=131", "--ignore=D100"]
        exclude: ^src/(test.py|test.ipynb)
