[tool.black]
line-length = 131
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.pycln]
all = true

[tool.isort]
profile='black'
multi_line_output = 3
